version: "3"

services:

    api:
        build: "."
        container_name: NG_CASH_API
        restart: always
        expose:
            - 3001
        ports:
            - "3001:3001"
        depends_on:
            - db

    db:
        image: postgres
        restart: always
        container_name: NG_CASH_DB
        expose:
            - 5432
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: ng_cash_db
